openapi: 3.1.0
info:
  version: 1.0.0
  title: LogisticApp
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is a documentation of Logistic-App
tags:
  - name: Auth
    description: Auth operations.
  - name: Trips
    description: Operations about trips by user.
  - name: AdminTrips
    description: Operations about trips by admin.
  - name: User
    description: User operations.
servers:
  - url: http://127.0.0.1:8080
  - url: https://logistic-app-wchv.onrender.com
paths:
  /auth/register:
    post:
      $ref: ../swagger/paths/auth/postRegister.yaml
  /auth/login:
    post:
      $ref: ../swagger/paths/auth/postLogin.yaml
  # /auth/info:
  #   get:
  #     $ref: ../swagger/paths/auth/getInfo.yaml
  # /auth:
  #   patch:
  #     $ref: ../swagger/paths/auth/patchUser.yaml
  /auth/logout:
    post:
      $ref: ../swagger/paths/auth/postLogout.yaml
  /auth/refresh:
    post:
      $ref: ../swagger/paths/auth/postRefresh.yaml
  /users:
    get:
      $ref: ../swagger/paths/user/getAllUsers.yaml
  /trips:
    post:
      $ref: ../swagger/paths/trips/postTrip.yaml
    get:
      $ref: ../swagger/paths/trips/getTrips.yaml
  /trips/{id}:
    get:
      $ref: ../swagger/paths/trips/{id}/get.yaml
    delete:
      $ref: ../swagger/paths/trips/{id}/delete.yaml
    put:
      $ref: ../swagger/paths/trips/{id}/put.yaml
  /admintrips:
    # post:
    #   $ref: ../swagger/paths/admintrips/postTrip.yaml
    get:
      $ref: ../swagger/paths/admintrips/getTrips.yaml
  /admintrips/{id}:
    get:
      $ref: ../swagger/paths/admintrips/{id}/get.yaml
    delete:
      $ref: ../swagger/paths/admintrips/{id}/delete.yaml
    put:
      $ref: ../swagger/paths/admintrips/{id}/put.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
